interface TravelItem {
  Id?: number
  Title?: string
  Subject?: string
  Status?: string
  OCONUS?: string
  OCONUSLocation?: string
  OCONUSApprovedBy?: string
  OCONUSApprovedOn?: string
  OCONUSApprovedEmail?: string
  StartTime?: string
  EndTime?: string
  WorkPlan?: string
  WorkPlanText?: string
  WorkPlanNumber?: string
  Company?: string
  TravelFrom?: string
  TravelTo?: string
  Travelers?: string
  TravelersText?: string
  Sponsor?: string
  POCName?: string
  POCEmail?: string
  POCPhone?: string
  Comments?: string
  Clearance?: string
  VisitRequest?: string
  SecurityAction?: string
  SecurityActionCompleted?: string
  PreApproved?: string
  Approved?: string
  EstimatedCost?: number
  IndexNumber?: string
  TripReport?: string
  TripReportLink?: string
  Created?: string
  InternalData?: string
  etag?: string
  uri?: string
}
export { TravelItem }
